name: cron job

on:
  schedule:
    - cron: "0 6,12,18 * * *"
  workflow_dispatch:
jobs:
  run_cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          node index.js > /dev/null 2>&1 &
          sleep 5 # Give some time for the server to start

      - name: Run cron job
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
        run: node cron.js
